export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST";
export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const GET_PUBLIC_COURSES = 'GET_PUBLIC_COURSES';
export const SET_LIST = 'SET_LIST';
export const LIST_FAIL = 'LIST_FAIL';

export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const GET_COURSE_SHARED_SUCCESS = 'GET_COURSE_SHARED_SUCCESS';
export const GET_COURSE_SHARED_FAIL = 'GET_COURSE_SHARED_FAIL';
export const GET_USER_ROLES = 'GET_USER_ROLES';
export const GET_USER_ROLES_FAIL = 'GET_USER_ROLES_FAIL';
export const GET_FLIP_CARDS = 'GET_FLIP_CARDS';
export const GET_FLIP_CARDS_FAIL = 'GET_FLIP_CARDS_FAIL';
