export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";

export const GET_PUBLIC_COURSES = 'GET_PUBLIC_COURSES';
export const SET_LIST = 'SET_LIST';
export const LIST_FAIL = 'LIST_FAIL';

export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';
export const GET_COURSE_SHARED_SUCCESS = 'GET_COURSE_SHARED_SUCCESS';
export const GET_COURSE_SHARED_FAIL = 'GET_COURSE_SHARED_FAIL';
export const GET_FLIP_CARDS = 'GET_FLIP_CARDS';
export const GET_FLIP_CARDS_FAIL = 'GET_FLIP_CARDS_FAIL';

